version: "3"

env:
  GOAMD64: v3

tasks:
  default: task --list-all

  run:
    env:
      REDIS_ADDR: "127.0.0.1:6379"
    cmds:
      - go run -v ./cmd/server/

  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -o server ./cmd/server/main.go
      - strip server

  test:
    cmds:
      - ginkgo run --tags test --fail-fast --randomize-all -r {{.CLI_ARGS}} ./test/

  test-parallel:
    cmds:
      - ginkgo run --tags test -p --fail-fast --randomize-all -r {{.CLI_ARGS}} ./test/

  cover:
    cmds:
      # -coverpkg=$(fd . internal/ -t d -x echo github.com/knightpp/alias-server/{} | tr '\n' ',') \
      - >
        go test \
          -timeout 5s \
          -tags test \
          -coverpkg=./... \
          -coverprofile=coverage.out \
          ./...
      - go tool cover -html=coverage.out

  up: "docker compose up {{.CLI_ARGS}}"

  gen: go generate ./...
