version: "3"

tasks:
  default: task --list-all

  run:
    env:
      REDIS_ADDR: "127.0.0.1:6379"
    cmds:
      - go run -v ./cmd/server/

  build:
    env:
      GOAMD64: v3
      CGO_ENABLED: 0

    cmds:
      - go build -o server ./cmd/server/main.go
      - strip server

  test:
    cmds:
      - >
        go test \
          -coverpkg=$(fd . internal/ -t d -x echo github.com/knightpp/alias-server/{} | tr '\n' ',') \
          -coverprofile=cover.out \
          ./test/socket/
      - go tool cover -html=cover.out

  up: "docker compose up {{.CLI_ARGS}}"

  gen: go generate ./...
