version: "3"

tasks:
  default: task --list-all

  run:
    env:
      REDIS_ADDR: "127.0.0.1:6379"
    cmds:
      - go run -v ./cmd/server/

  build:
    env:
      GOAMD64: v3
      CGO_ENABLED: 0

    cmds:
      - go build -o server ./cmd/server/main.go
      - strip server

  test:
    cmds:
      # -coverpkg=$(fd . internal/ -t d -x echo github.com/knightpp/alias-server/{} | tr '\n' ',') \
      - >
        go test \
          -tags test \
          -coverpkg=./... \
          -coverprofile=coverage.out \
          -race \
          ./test/socket/

  cover:
    deps:
      - test
    cmds:
      - go tool cover -html=coverage.out

  up: "docker compose up {{.CLI_ARGS}}"

  gen: go generate ./...
