version: "3"

tasks:
  default: task --list-all

  run:
    env:
      REDIS_ADDR: "127.0.0.1:6379"
    cmds:
      - go run -v ./cmd/server/

  build:
    env:
      GOAMD64: v3
      CGO_ENABLED: 0

    cmds:
      - go build -tags=nomsgpack -o server ./cmd/server/main.go
      - strip server

  up: "docker compose up {{.CLI_ARGS}}"

  gen: go generate ./...
