version: "3"

tasks:
  default: task --list-all

  build:
    env:
      GOAMD64: v3
      CGO_ENABLED: 0

    cmds:
      - go build -tags=nomsgpack -o server ./cmd/server/main.go
      - strip server

  gen: go generate ./...
