# fly.toml app configuration file generated for alias-redis on 2023-04-29T13:07:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alias-redis"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[mounts]]
  source = "redis_volume"
  destination = "/data"
  processes = ["app"]
